import type { MapMarker } from '../types';

/**
 * Generate GPX XML string from markers
 */
export function generateGPX(markers: MapMarker[], trackName: string = 'Elevation Track'): string {
  const timestamp = new Date().toISOString();
  
  const trackPoints = markers
    .filter(m => m.elevation !== null)
    .map(m => {
      const time = new Date(m.timestamp).toISOString();
      return {
        lat: m.position.lat,
        lon: m.position.lng,
        ele: m.elevation!,
        time,
      };
    });

  const gpxHeader = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Elevation Detector" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(trackName)}</name>
    <desc>Elevation track generated by Elevation Detector</desc>
    <time>${timestamp}</time>
  </metadata>
  <trk>
    <name>${escapeXml(trackName)}</name>
    <desc>Elevation track with ${trackPoints.length} points</desc>`;

  const trackPointElements = trackPoints
    .map(point => `
    <trkpt lat="${point.lat}" lon="${point.lon}">
      <ele>${point.ele}</ele>
      <time>${point.time}</time>
    </trkpt>`)
    .join('');

  const gpxFooter = `
  </trk>
</gpx>`;

  return gpxHeader + trackPointElements + gpxFooter;
}

/**
 * Export markers to GPX file
 */
export function exportMarkersToGPX(markers: MapMarker[], trackName: string = 'Elevation Track'): void {
  const gpx = generateGPX(markers, trackName);
  
  const blob = new Blob([gpx], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${trackName.replace(/\s+/g, '_')}.gpx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * Calculate GPX statistics
 */
export function getGPXStats(markers: MapMarker[]): {
  distance: number;
  elevationGain: number;
  elevationLoss: number;
  points: number;
} {
  const validMarkers = markers.filter(m => m.elevation !== null);
  
  if (validMarkers.length < 2) {
    return {
      distance: 0,
      elevationGain: 0,
      elevationLoss: 0,
      points: validMarkers.length,
    };
  }

  let distance = 0;
  let elevationGain = 0;
  let elevationLoss = 0;

  for (let i = 1; i < validMarkers.length; i++) {
    const prev = validMarkers[i - 1];
    const curr = validMarkers[i];

    distance += haversineDistance(prev.position, curr.position);

    if (prev.elevation !== null && curr.elevation !== null) {
      const change = curr.elevation - prev.elevation;
      if (change > 0) {
        elevationGain += change;
      } else {
        elevationLoss += Math.abs(change);
      }
    }
  }

  return {
    distance,
    elevationGain,
    elevationLoss,
    points: validMarkers.length,
  };
}

/**
 * Calculate haversine distance between two coordinates (in meters)
 */
function haversineDistance(coord1: { lat: number; lng: number }, coord2: { lat: number; lng: number }): number {
  const R = 6371000;
  const phi1 = (coord1.lat * Math.PI) / 180;
  const phi2 = (coord2.lat * Math.PI) / 180;
  const deltaPhi = ((coord2.lat - coord1.lat) * Math.PI) / 180;
  const deltaLambda = ((coord2.lng - coord1.lng) * Math.PI) / 180;

  const a =
    Math.sin(deltaPhi / 2) * Math.sin(deltaPhi / 2) +
    Math.cos(phi1) * Math.cos(phi2) * Math.sin(deltaLambda / 2) * Math.sin(deltaLambda / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
}

/**
 * Format distance in human-readable format
 */
export function formatDistance(meters: number): string {
  if (meters < 1000) {
    return `${Math.round(meters)} m`;
  }
  const km = meters / 1000;
  return `${km.toFixed(2)} km`;
}

/**
 * Escape XML special characters
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
